version: '3.7'

services:
  automation-demoqa:
    image: python:3.11-slim-bullseye
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    command: "pytest --headless=true"
    working_dir: /src