version: '3'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
      - allure-results:/src/allure-results
    ports:
      - "4445:4444"
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4445:4444"

volumes:
  allure-results: